GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###

DELETE  http://127.0.0.1:8000/products/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwOTA5NTYwLCJpYXQiOjE3NzA5MDkyNjAsImp0aSI6IjNmNDY0NWQxNDA4NDQ3NTE5NTJjMjExYzNiMjFhODk1IiwidXNlcl9pZCI6IjEifQ.QXoEkdJqoG2BJfdnSXb2GDhRfhra5TQcxf2kMhme7pw

###
PUT http://127.0.0.1:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwOTA5NTYwLCJpYXQiOjE3NzA5MDkyNjAsImp0aSI6IjNmNDY0NWQxNDA4NDQ3NTE5NTJjMjExYzNiMjFhODk1IiwidXNlcl9pZCI6IjEifQ.QXoEkdJqoG2BJfdnSXb2GDhRfhra5TQcxf2kMhme7pw

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "name": "Television",
    "price": 300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDk5NDcwNSwiaWF0IjoxNzcwOTA4MzA1LCJqdGkiOiI1NDNhY2Q5MGY2ZTQ0MWY2OTgxYmE3YWE3OTZiYWYzMyIsInVzZXJfaWQiOiIyIn0.9Ei9EIp5cQfYxhW-vAxLxFF3uVkN-kHUTFOW8AmgMsk"
}

###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwOTA3NjgwLCJpYXQiOjE3NzA5MDczODAsImp0aSI6IjQwODUxMzdiMjIxODQ3ZjY5ZDRjMjAwMTlhYjdlNWFmIiwidXNlcl9pZCI6IjIifQ.7b1UcfydayzhK3k3y9hNR_YZQKENYrL1Tjh5RU7Cky0

###

GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDAyNjI1LCJpYXQiOjE3NzEwMDIzMjUsImp0aSI6Ijg1ZTU3ODg0MDYwZDRiZTc4ZDcwMmYzMDBlODA1MzliIiwidXNlcl9pZCI6IjIifQ.vYfFCn-MfzgPrgP7fcTniuQ9wqWGvQYmCEzgzd4SG2w

###

GET http://127.0.0.1:8000/orders/74b00f00-330d-490e-ba7a-a15facc14974 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDA3NzM5LCJpYXQiOjE3NzEwMDc0MzksImp0aSI6IjljYzY2NWQ3NDIxMjQ4MjNhMzEwN2IzYjQ2OWQzNGNjIiwidXNlcl9pZCI6IjEifQ.V2raaRGiTh1Svwt5qus6jUfwjGfkDfxxnWCgA5y5d0E

###

POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDA1NDgwLCJpYXQiOjE3NzEwMDUxODAsImp0aSI6ImUxNDhkMWIyZWI1YjRjYmU5N2Q0YjcxYTgzZTIwZTRiIiwidXNlcl9pZCI6IjEifQ.WHyirPUjGl3tgcF7haZGz8UOkAJHNq9PKMM4SD7K1cs

{
    "status": "Pending",
    "items": [
        {
            "product":4,
            "quantity":2
        },
        {
            "product":3,
            "quantity":1
        }
    ]
}

###

PUT http://127.0.0.1:8000/orders/74b00f00-330d-490e-ba7a-a15facc14974/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDA3NzM5LCJpYXQiOjE3NzEwMDc0MzksImp0aSI6IjljYzY2NWQ3NDIxMjQ4MjNhMzEwN2IzYjQ2OWQzNGNjIiwidXNlcl9pZCI6IjEifQ.V2raaRGiTh1Svwt5qus6jUfwjGfkDfxxnWCgA5y5d0E

{
    "status": "Pending",
    "items": [
        {
            "product":4,
            "quantity":3
        },
        {
            "product":3,
            "quantity":5
        }
    ]
}

###

DELETE http://127.0.0.1:8000/orders/74b00f00-330d-490e-ba7a-a15facc14974/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMDA3NzM5LCJpYXQiOjE3NzEwMDc0MzksImp0aSI6IjljYzY2NWQ3NDIxMjQ4MjNhMzEwN2IzYjQ2OWQzNGNjIiwidXNlcl9pZCI6IjEifQ.V2raaRGiTh1Svwt5qus6jUfwjGfkDfxxnWCgA5y5d0E